# Generated by Django 6.0.5 on 2026-06-13 13:52

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0236_moduletype_component_counts'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('pve_sync_plugin', '0005_align_netboxmodel_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbsServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('pbs_host', models.CharField(max_length=200)),
                ('pbs_token_name', models.CharField(max_length=100)),
                ('pbs_token_secret', models.CharField(max_length=200)),
                ('pbs_verify_ssl', models.BooleanField(default=False)),
                ('pbs_node_name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'PBS Server Config',
                'verbose_name_plural': 'PBS Server Configs',
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.RenameIndex(
            model_name='pvesyncjob',
            new_name='pve_sync_pl_status_75c10e_idx',
            old_name='pve_sync_pv_status_1b8f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='pvesyncjob',
            new_name='pve_sync_pl_cluster_f5f1cc_idx',
            old_name='pve_sync_pv_cluster_c7bb8f_idx',
        ),
        migrations.RenameIndex(
            model_name='pvewebhookevent',
            new_name='pve_sync_pl_event_t_5411b8_idx',
            old_name='pve_sync_pv_event_t_5a9362_idx',
        ),
        migrations.RenameIndex(
            model_name='pvewebhookevent',
            new_name='pve_sync_pl_vmid_e99644_idx',
            old_name='pve_sync_pv_vmid_90e5c1_idx',
        ),
        migrations.RenameIndex(
            model_name='pvewebhookevent',
            new_name='pve_sync_pl_receive_1176ec_idx',
            old_name='pve_sync_pv_receive_ce4cf2_idx',
        ),
        migrations.RemoveField(
            model_name='pvepluginsettings',
            name='pve_api_host',
        ),
        migrations.RemoveField(
            model_name='pvepluginsettings',
            name='pve_api_secret',
        ),
        migrations.RemoveField(
            model_name='pvepluginsettings',
            name='pve_api_token',
        ),
        migrations.RemoveField(
            model_name='pvepluginsettings',
            name='pve_api_user',
        ),
        migrations.RemoveField(
            model_name='pvepluginsettings',
            name='pve_api_verify_ssl',
        ),
        migrations.AddField(
            model_name='pvebackupstatus',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='pveclusterconfig',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='pvepluginsettings',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='pvesyncjob',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='pvewebhookevent',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='pbsserverconfig',
            name='netbox_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbs_servers', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='pbsserverconfig',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
