# Generated by Django 6.0.5 on 2026-06-22 16:57

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('pve_sync_plugin', '0014_vmprovisioninglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmprovisioninglog',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='vmprovisioninglog',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.CreateModel(
            name='PveVmTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('upid', models.CharField(max_length=300, unique=True)),
                ('vmid', models.IntegerField()),
                ('vm_name', models.CharField(blank=True, max_length=200)),
                ('cluster_name', models.CharField(max_length=100)),
                ('node', models.CharField(max_length=100)),
                ('task_type', models.CharField(max_length=30)),
                ('operator', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('notified_telegram', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'VM Task Log',
                'verbose_name_plural': 'VM Task Logs',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['vmid', 'cluster_name'], name='pve_sync_pl_vmid_00b115_idx'), models.Index(fields=['task_type'], name='pve_sync_pl_task_ty_0f86cb_idx'), models.Index(fields=['operator'], name='pve_sync_pl_operato_6b34b5_idx'), models.Index(fields=['start_time'], name='pve_sync_pl_start_t_dac39f_idx')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
