# Generated by Django 6.0.5 on 2026-06-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pve_sync_plugin', '0015_pvevmtasklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvevmtasklog',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
